//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xna.Helpers._3D {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EffectsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EffectsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xna.Helpers._3D.EffectsResource", typeof(EffectsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] BillboardEffect {
            get {
                object obj = ResourceManager.GetObject("BillboardEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CubeMapReflect {
            get {
                object obj = ResourceManager.GetObject("CubeMapReflect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GaussianBlur {
            get {
                object obj = ResourceManager.GetObject("GaussianBlur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LightingEffect {
            get {
                object obj = ResourceManager.GetObject("LightingEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MultiLightingEffect {
            get {
                object obj = ResourceManager.GetObject("MultiLightingEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PointLightEffect {
            get {
                object obj = ResourceManager.GetObject("PointLightEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PPDepthNormal {
            get {
                object obj = ResourceManager.GetObject("PPDepthNormal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PPLight {
            get {
                object obj = ResourceManager.GetObject("PPLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PPLightMesh {
            get {
                object obj = ResourceManager.GetObject("PPLightMesh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PPModel {
            get {
                object obj = ResourceManager.GetObject("PPModel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PPShared {
            get {
                object obj = ResourceManager.GetObject("PPShared", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ProjectedTexture {
            get {
                object obj = ResourceManager.GetObject("ProjectedTexture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowDepthEffect {
            get {
                object obj = ResourceManager.GetObject("ShadowDepthEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ShadowMapping {
            get {
                object obj = ResourceManager.GetObject("ShadowMapping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SimpleEffect {
            get {
                object obj = ResourceManager.GetObject("SimpleEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] skysphere_effect {
            get {
                object obj = ResourceManager.GetObject("skysphere_effect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SpotLightEffect {
            get {
                object obj = ResourceManager.GetObject("SpotLightEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TerrainEffect {
            get {
                object obj = ResourceManager.GetObject("TerrainEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WaterEffect {
            get {
                object obj = ResourceManager.GetObject("WaterEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
